# Generated by Django 3.1.7 on 2021-03-14 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20210314_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='name',
            new_name='question',
        ),
    ]
